name: CI Build Workflow

on: [push]

jobs:
  ci-build:
    name: CI Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11.4"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      run: |
        echo "done"

