name: Docker Image Build

on:
  workflow_run:
    workflows: [CI Build Workflow]
    branches: [main]
    types:
      - completed
  push:
    branches: main

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check if the CI-Build workflow was successful
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
            echo "The triggering workflow 'CI Build Workflow' did not succeed. Skipping this workflow run."
            exit 0
          fi
      
      - name: Check if this event is a merged pull request
        run: |
          if [ "${{ github.event.workflow_run.event }}" != "pull_request" ] || [ "${{ github.event.workflow_run.pull_request.merged }}" != "true" ]; then
            echo "The triggering event is not a merged pull request. Skipping this workflow run." 
            # exit 0
            gh run cancel ${{ github.run_id }}
            gh run watch ${{ github.run_id }}
          fi

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: poonamsabharwal
          password: dckr_pat_J61TsbBzpwqA4zOGTvtuiuvRprg
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: poonamsabharwal/citadel-idp-frontend:latest
  
  
