name: Docker Image Build

on:
  workflow_run:
    workflows: [CI Build Workflow]
    branches: [main]
    types:
      - completed
    
jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check if the CI-Build workflow was successful
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
            echo "The triggering workflow 'CI Build Workflow' did not succeed. Skipping this workflow run."
            exit 1
          fi
      
      - name: Check if this event is a merged pull request
        run: |
          if [ "${{ github.event.workflow_run.event }}" != "pull_request" ] || [ "${{ github.event.pull_request.merged }}" != "true" ]; then
            echo "The triggering event is not a merged pull request. Skipping this workflow run."
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        run: |
          echo "done 2"
  
