name: CI Build Workflow

on: [push]

jobs:
  ci-build:
    name: CI Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.4"]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
        
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py' | grep -v "dummy") || true


  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: ci-build
    steps:
    - name: Sleep and Run
      run: |
        echo "Sleeping for 3"
        sleep 3

  
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: vireshwali@gmail.com
          password: dckr_pat_s-gXRLJadJLRE1XRV1OGxpoVRW4
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: vireshwali/test-21:latest
  
  
